//apply plugin: 'com.android.library'
//apply plugin: 'com.github.dcendents.android-maven'
//group = 'com.github.youlookwhat'
plugins {
    id 'com.android.library'
    id 'maven-publish'
}

afterEvaluate {
    publishing {
        publications {
            release(MavenPublication) {
//                from components.release
                from components.findByName('release')
                groupId = 'me.jingbin.web'
                artifactId = 'ByWebView'
                version = '1.2.2'
            }
        }
    }
}

android {
    namespace 'me.jingbin.web'
    compileSdk 34

    defaultConfig {
        minSdk 14
        targetSdk 34

        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'

    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    compileOnly 'com.google.android.material:material:1.0.0'
//    testImplementation 'junit:junit:4.12'
//    androidTestImplementation 'com.android.support.test:runner:1.0.2'
//    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}
